# Generated by Django 2.0 on 2017-12-29 12:08

import discord_auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAuthToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(db_index=True, default=discord_auth.models.get_random_token, max_length=20)),
            ],
        ),
    ]
