# Generated by Django 2.0 on 2018-01-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('discord_auth', '0002_discord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_role', to='auth.Group')),
            ],
        ),
    ]
