# Generated by Django 2.0 on 2018-01-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0003_discord_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordrole',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
