# Generated by Django 2.0 on 2018-01-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0005_role_group_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordrole',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
