# Generated by Django 2.0 on 2018-10-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0008_role_to_group_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignableRole',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord_auth.DiscordRole')),
            ],
        ),
    ]
