# Generated by Django 2.0 on 2017-12-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evedata',
            options={'verbose_name': 'EVE Data', 'verbose_name_plural': 'EVE Data'},
        ),
    ]
