# Generated by Django 2.0 on 2017-12-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0002_change_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedata',
            name='full_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
