# Generated by Django 2.0 on 2018-04-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_auth', '0003_evedata_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evedata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='evedata',
            name='last_name',
        ),
    ]
